Repository mybb/mybb, pull requests merged in 2018-05, with the labels that each got.

#3187 Fixes #3186 Save PM as Draft issue
  inc/datahandlers/pm.php
Labels: 1.8

#3199 AIM Removal
  admin/modules/user/users.php
  inc/datahandlers/user.php
  inc/languages/english/admin/user_users.lang.php
  inc/languages/english/member.lang.php
  inc/languages/english/memberlist.lang.php
  inc/languages/english/misc.lang.php
  inc/languages/english/modcp.lang.php
  inc/languages/english/usercp.lang.php
  install/index.php
  install/resources/mybb_theme.xml
  install/resources/mysql_db_tables.php
  install/resources/pgsql_db_tables.php
  install/resources/settings.xml
  install/resources/sqlite_db_tables.php
  install/resources/upgrade43.php
  member.php
  memberlist.php
  misc.php
  modcp.php
  usercp.php
Labels: 1.8

#3174 Fixes #2844 #2801 ACP Set '0 to disable' issue
  inc/functions_upload.php
  install/resources/settings.xml
  install/resources/upgrade43.php
Labels: 1.8

#3195 Fixes #2632 begin with bots
  index.php
  portal.php
Labels: 1.8

#3086 mycode in not removed in email notifications + fix for removing neste…
  inc/class_parser.php
  inc/datahandlers/post.php
Labels: 1.8, bug

#3188 Fixes #3173 search forum filtering
  search.php
Labels: 1.8

#3196 Fixes #2137 Stylesheet order reset after importing a theme
  admin/inc/functions_themes.php
Labels: 1.8

#3190 Fixes #1890 Sort threads by prefix bug
  forumdisplay.php
Labels: 1.8

#3053 Working on #2972 Template Conversion to Twig Format (video)
  global.php
  inc/class_parser.php
  inc/views/base/parser/video.twig
Labels: 1.9

#3200 Fixes #3081 Empty Email Address can result in PHP Warning on user validation
  inc/datahandlers/user.php
Labels: 1.8

#3117 Fixes #3113 – Added default language to set_language()
  inc/class_language.php
Labels: 1.8

#3142 Working on #2972 Template Conversion to Twig Format (usercp usergroups)
  inc/views/base/usercp/usergroups.twig
  usercp.php
Labels: 1.9

#3194 Fixes #299 Unwanted CSS Path Modifier Removal
  admin/inc/functions_themes.php
  admin/modules/style/themes.php
Labels: 1.8

#3219 Fixes #3215 Add SameSite=lax flag to authentication cookies
  admin/index.php
  admin/modules/config/settings.php
  inc/datahandlers/login.php
  inc/functions.php
  install/index.php
  install/resources/settings.xml
  install/resources/upgrade43.php
  install/upgrade.php
  member.php
  usercp.php
Labels: 1.8

#3207 Convert user CP atatchments page to Twig
  inc/views/base/usercp/attachments.twig
  inc/views/base/usercp/attachments/row.twig
  showthread.php
  usercp.php
Labels: 1.9, s:fixed

#3211 Working on #2972 Template Conversion to Twig Format (modcp_modlogs)
  inc/views/base/modcp/modlogs.twig
  inc/views/base/modcp/modlogs/item.twig
  modcp.php
Labels: 1.9

#3162 Working on #2972 Template Conversion to Twig Format (reputation.php)
  inc/views/base/reputation/add.twig
  inc/views/base/reputation/add_error.twig
  inc/views/base/reputation/add_error_nomodal.twig
  inc/views/base/reputation/added.twig
  inc/views/base/reputation/deleted.twig
  inc/views/base/reputation/reputation.twig
  inc/views/base/reputation/reputation_vote.twig
  reputation.php
Labels: 1.9

#3221 Working on #2972 Template Conversion to Twig Format (modcp_ipsearch)
  inc/languages/english/modcp.lang.php
  inc/views/base/modcp/iplookup.twig
  inc/views/base/modcp/iplookup_modal.twig
  inc/views/base/modcp/ipsearch.twig
  modcp.php
Labels: 1.9

#3218 Fixes #2094 Smart bug in color name
  admin/modules/style/themes.php
  inc/languages/english/admin/style_themes.lang.php
Labels: 1.8

#3132 Fixes #3128 Extra </li> in lists output by the parser
  inc/class_parser.php
Labels: 1.8, s:feedback
