Repository mybb/mybb, pull requests merged in 2018-07, with the labels that each got.

#3281 Fixes #3241 .prop('checked') doesn't trigger change events
  jscripts/inline_moderation.js
Labels: 1.9

#3283 Update Collapse for Javascript Updates #3282
  jscripts/general.js
Labels: 1.9

#3302 Missed out template version update in 1.8.16
  install/resources/mybb_theme.xml
Labels: 1.8

#3298 Fixed missing parentheses
  install/resources/upgrade43.php
Labels: 1.8

#3300 Strange comma in whosonline
  index.php
  portal.php
Labels: 1.8

#3301 Fixes login in portal page
  install/resources/mybb_theme.xml
Labels: 1.8

#3299 Fix Unable to Report in 1.8.16
  report.php
Labels: 1.8

#3305 Fix #3304 - conditional sepator
  inc/languages/english/index.lang.php
  index.php
  install/resources/mybb_theme.xml
Labels: 1.8

#3313 Fixes #3310 - update general.js
  install/resources/mybb_theme.xml
  jscripts/general.js
Labels: 1.8

#3322 Fixes #3321 by updating CSS class
  install/resources/mybb_theme.xml
Labels: 1.8

#3328 Add missing post key
  install/resources/mybb_theme.xml
Labels: 1.8

#3314 Bump template version to 1817 for merged PRs
  install/resources/mybb_theme.xml
Labels: 1.8

#3334 Collapse fix
  jscripts/general.js
Labels: 1.9, bug

#3315 Fixes user stars not showing correctly
  calendar.php
  inc/functions_post.php
  install/resources/mybb_theme.xml
  member.php
  memberlist.php
  modcp.php
  reputation.php
Labels: 1.8

#3338 Fixes #3337 Unable to retrieve guest permissions while logged in
  inc/functions.php
Labels: 1.8

#3130 Feature: parser unit tests
  inc/class_parser.php
  inc/src/Twig/Extensions/ThemeExtension.php
  inc/views/base/parser/mycodes/img.twig
  inc/views/base/parser/mycodes/url.twig
  tests/Unit/ExampleTest.php
  tests/Unit/ParserTest.php
  tests/Unit/Traits/LegacyCoreAwareTest.php
  tests/bootstrap.php
Labels: 1.9, enhancement

#3346 Fixes #3345 – Cookies not wiped if using the modal to log in
  global.php
Labels: 1.8

#3255 Fixes #2540 Issue with adminCP login page and redirection
  admin/inc/class_page.php
Labels: 1.8

#3351 Fixes #3347 Revising usage of short array syntax in showteam.php
  showteam.php
Labels: 1.8

#3352 Fixes #3340 Embedded videos have extraneous vertical space above and …
  inc/class_parser.php
Labels: 1.8

#3350 Fixes #3349 Unnecessary variable removal from templates
  install/resources/mybb_theme.xml
Labels: 1.8

#3355 Fixes #3354 Invalid regular expression in Bad words filter throwing PHP warning
  admin/modules/config/badwords.php
  inc/languages/english/admin/config_badwords.lang.php
Labels: 1.8

#3364 Fixes #3363 SQLite ShowTeam Error
  showteam.php
Labels: 1.8

#3335 Trigger event on selectall change
  admin/modules/user/users.php
  install/resources/mybb_theme.xml
  jscripts/inline_moderation.js
Labels: 1.8, enhancement

#3356 Fixes #3295 Reset password should have captcha or require username too.
  install/resources/mybb_theme.xml
  member.php
Labels: 1.8

#3342 Fixes #3341 Thread Subscription Bug
  inc/functions.php
  newreply.php
  newthread.php
Labels: 1.8

#3361 Fixes #2659 Double recipients with private messages
  install/resources/mybb_theme.xml
  private.php
Labels: 1.8

#3365 Fixes #3245, #3344 Video MyCode Bug
  global.php
  inc/class_parser.php
  inc/functions.php
  inc/languages/english/admin/global.lang.php
  inc/languages/english/global.lang.php
  install/resources/mybb_theme.xml
  jscripts/bbcodes_sceditor.js
Labels: 1.8

#3360 Fixes #3359 Settings `gid` is blank in ACP settings search page
  admin/modules/config/settings.php
Labels: 1.8

#3353 Fixes #3262 Bad word filter
  admin/modules/config/badwords.php
  inc/class_parser.php
  inc/languages/english/admin/config_badwords.lang.php
Labels: 1.8

#3357 Fixes #3144 MyCode affects signature length Issue
  inc/class_parser.php
  inc/datahandlers/user.php
Labels: 1.8

#3358 Fixes #3192 Avatar dimension separator consistency
  admin/modules/config/settings.php
  admin/modules/user/users.php
  inc/functions.php
  inc/functions_upload.php
  inc/languages/english/admin/config_settings.lang.php
  install/resources/settings.xml
  install/resources/upgrade12.php
  usercp.php
Labels: 1.8

#3273 Fixed partial rebase issue with forumdisplay
  forumdisplay.php
  inc/views/base/forumdisplay/forumdisplay.twig
  inc/views/base/forumdisplay/thread.twig
Labels: 1.9

#3274 #2976 - add `my_date` filter and other useful twig functions
  inc/languages/english/global.lang.php
  inc/src/Twig/Extensions/CoreExtension.php
  inc/src/bootstrap.php
  inc/views/base/member/profile.twig
  inc/views/base/partials/time.twig
  inc/views/base/postbit/postbit.twig
  member.php
Labels: 1.9

#3369 Fixes #3368 Syntax error in MyBB 1.8.17
  inc/datahandlers/post.php
  inc/functions.php
Labels: 1.8
