Repository mybb/mybb, pull requests merged in 2018-10, with the labels that each got.

#3460 Fixes #3459 - Search feature improvements
  inc/functions_search.php
  inc/languages/english/search.lang.php
  install/resources/mybb_theme.xml
Labels: b:1.8, t:enhancement

#3446 Fixes #3427 Remove archive mode
  announcements.php
  archive/global.php
  archive/index.php
  archive/print.css
  archive/screen.css
  forumdisplay.php
  global.php
  inc/class_parser.php
  inc/functions.php
  inc/functions_archive.php
  inc/init.php
  inc/languages/english/archive.lang.php
  inc/languages/english/global.lang.php
  inc/src/Utilities/BreadcrumbManager.php
  install/resources/settings.xml
  showthread.php
Labels: b:1.9

#3444 Fixes #3443 MyBB ACP - Latest announcements scraping wrong and repeated content
  admin/modules/home/index.php
Labels: b:1.8

#3438 fixes #3430 ACP settings search option hardcoded only for english language
  admin/modules/config/settings.php
Labels: b:1.8, s:confirmed

#3406 Fixes #3403 - New plugin hooks in user CP
  usercp.php
Labels: b:1.8

#3418 Fixes #3417 - Last Active shown for hidden users
  inc/languages/english/usercp.lang.php
Labels: b:1.8

#3462 Reorganising bootstrap.php, changing how Twig is registered
  composer.json
  composer.lock
  inc/src/Application.php
  inc/src/ServiceProvider.php
  inc/src/Twig/Extensions/CoreExtension.php
  inc/src/Twig/ServiceProvider.php
  inc/src/bootstrap.php
  inc/src/functions.php
Labels: b:1.9

#3396 Fixes #3291 - Issue with Thread Prefix
  install/resources/mybb_theme.xml
Labels: b:1.8

#3474 Fix #3473 - Add index_showteamlink to templatelist
  index.php
Labels: b:1.8

#3478 Fix #3477 - Include back trace in error logs and error emails
  inc/class_error.php
Labels: b:1.8
