Repository mybb/mybb, pull requests merged in 2018-03, with the labels that each got.

#3069 Working on #2972 Template Conversion to Twig Format (multipage)
  inc/functions.php
  inc/views/base/partials/multipage.twig
Labels: 1.9

#3065 Working on #2972 Template Conversion to Twig Format (showteam.php)
  inc/views/base/showteam/showteam.twig
  showteam.php
Labels: 1.9

#3070 Working on #2972 Template Conversion to Twig Format (IP Addresses)
  inc/functions_post.php
  inc/views/base/moderation/getip.twig
  inc/views/base/moderation/getip_modal.twig
  inc/views/base/moderation/getpmip.twig
  inc/views/base/moderation/getpmip_modal.twig
  inc/views/base/postbit/postbit.twig
  moderation.php
Labels: 1.9

#3072 Fixes #3071 Default Thread subscription mode in admin CP
  admin/modules/user/users.php
  inc/languages/english/admin/user_users.lang.php
Labels: 1.8

#3067 Fixed embedded videos not working after #2968
  inc/class_parser.php
Labels: 1.8, p:high
