Repository mybb/mybb, pull requests merged in 2018-08, with the labels that each got.

#3278 Fixes #3276 - PHP 7 multipage issue
  admin/modules/config/post_icons.php
  admin/modules/config/smilies.php
  admin/modules/tools/mailerrors.php
  admin/modules/tools/maillogs.php
  admin/modules/tools/statistics.php
  admin/modules/tools/warninglog.php
  admin/modules/user/awaiting_activation.php
  admin/modules/user/group_promotions.php
  admin/modules/user/users.php
  managegroup.php
  memberlist.php
  misc.php
  modcp.php
  private.php
  search.php
  usercp.php
Labels: 1.8

#3381 Fixes custom profile fields on install
  install/resources/mysql_db_tables.php
  install/resources/pgsql_db_tables.php
  install/resources/sqlite_db_tables.php
Labels: 1.9

#3370 Fixes #3367 - use table alias for title column
  admin/modules/style/templates.php
Labels: 1.8

#3375 Fixes #3287 Unable to view or add attachments if new post was saved as draft before posting
  attachment.php
Labels: 1.8

#3379 Fixes #3378 - Add a check box "remember_me"
  install/resources/mybb_theme.xml
Labels: 1.8

#3387 Working on #2972 – inc/functions.php cleanup
  inc/functions.php
  inc/views/base/forumdisplay/threadlist_prefixes.twig
  inc/views/base/postbit/reputation.twig
  inc/views/base/postbit/warninglevel.twig
Labels: 1.9

#3373 Fixes #3139 Attachment: a bug and a mod to allow multi-attachment selection
  editpost.php
  global.php
  inc/functions.php
  inc/functions_post.php
  inc/functions_upload.php
  inc/languages/english/global.lang.php
  inc/languages/english/messages.lang.php
  install/resources/mybb_theme.xml
  jscripts/post.js
  newreply.php
  newthread.php
Labels: 1.8

#3389 Fix #2921 SQL error on install due to reserved word in MySQL 8
  forumdisplay.php
  inc/db_mysql.php
  inc/db_mysqli.php
  install/resources/mysql_db_inserts.php
  install/resources/mysql_db_tables.php
  install/resources/upgrade17.php
  moderation.php
  showthread.php
Labels: 1.8

#3216 Resolves #2139 : Soft deleted threads and answers
  editpost.php
  inc/languages/english/moderation.lang.php
  inc/languages/english/ratethread.lang.php
  inc/languages/english/showthread.lang.php
  install/resources/mybb_theme.xml
  jscripts/thread.js
  moderation.php
  polls.php
  printthread.php
  ratethread.php
  showthread.php
  usercp.php
  xmlhttp.php
Labels: 1.8

#3390 Fixes #3139 Attachment: a bug and a mod to allow multi-attachment selection
  inc/functions_upload.php
Labels: 1.8

#3391 Fixes #3058 File Verification can wrongly parse mybb.com responses
  admin/modules/tools/file_verification.php
Labels: 1.8

#3399 Bad word filter - extended refinement
  inc/class_parser.php
Labels: 1.8

#3366 Add support for \Closure type hooks.
  inc/class_plugins.php
Labels: 1.9, enhancement

#3413 Fix #3409 by moving my_hash_equals
  inc/functions.php
  inc/functions_archive.php
  inc/functions_forumlist.php
  inc/functions_search.php
  inc/functions_user.php
Labels: b:1.8

#3394 Fixes #3393 - Grammar issue in upgrade script
  install/resources/language.lang.php
Labels: b:1.8
