Repository mybb/mybb, pull requests merged in 2018-06, with the labels that each got.

#3226 Add Prague, Bratislava to the timezones
  inc/languages/english/admin/global.lang.php
  inc/languages/english/global.lang.php
Labels: 1.8

#3201 Fix #2225 wordfilter cannot replace strings with * in them
  admin/modules/config/badwords.php
  inc/class_parser.php
  inc/languages/english/admin/config_badwords.lang.php
  install/resources/mysql_db_tables.php
  install/resources/pgsql_db_tables.php
  install/resources/sqlite_db_tables.php
  install/resources/upgrade43.php
Labels: 1.8

#3177 Fixes #3175 PM Postbit
  calendar.php
  inc/class_session.php
  inc/functions_post.php
  install/resources/mybb_theme.xml
  member.php
  memberlist.php
  modcp.php
  reputation.php
Labels: 1.8

#3115 Fixes #3109 – Maxloginattempts lockout
  global.php
  inc/datahandlers/login.php
  inc/functions.php
  install/resources/mybb_theme.xml
  install/resources/mysql_db_tables.php
  install/resources/pgsql_db_tables.php
  install/resources/sqlite_db_tables.php
  install/resources/upgrade43.php
  member.php
Labels: 1.8

#3217 Resolves #2140 Forum Team Display Enhancement
  admin/modules/config/settings.php
  inc/languages/english/showteam.lang.php
  index.php
  install/resources/mybb_theme.xml
  install/resources/settings.xml
  install/resources/upgrade43.php
  showteam.php
Labels: 1.8

#3231 Fixes #3228 PHP 7 Compatibility
  polls.php
Labels: 1.8

#3238 Fix #3237 - Smillie settings "Show on clickable list" doesn't take ef…
  misc.php
Labels: 1.8

#3236 Fixes #3170 MySQL error with strict mode if message too long
  inc/datahandlers/pm.php
  inc/datahandlers/post.php
  inc/languages/english/datahandler_pm.lang.php
Labels: 1.8

#3240 Fixes #2445 Host check code doesn't work anymore
  inc/functions_serverstats.php
Labels: 1.8

#3239 Fixes #3169 Private.php > Tracking Pagination Issue
  inc/functions.php
  install/resources/mybb_theme.xml
Labels: 1.8

#3045 Working on #2972 Template Conversion to Twig Format (error)
  editpost.php
  inc/functions.php
  inc/views/base/error/error.twig
  inc/views/base/error/inline.twig
  inc/views/base/error/no_permission.twig
Labels: 1.9

#3260 Working on #2972 Template Conversion to Twig Format (headerinclude)
  global.php
  inc/views/base/layouts/master.twig
Labels: 1.9

#3257 Adjustments for announcements (#2972)
  inc/functions_modcp.php
  inc/views/base/announcements/announcements.twig
  inc/views/base/modcp/announcements.twig
  inc/views/base/modcp/announcements/forum.twig
  inc/views/base/modcp/announcements_add.twig
  modcp.php
Labels: 1.9

#3261 Working on #2972 Template Conversion to Twig Format (usercp2)
  inc/functions_online.php
  inc/languages/english/messages.lang.php
  inc/views/base/usercp/subscribe_thread.twig
  install/resources/mybb_theme.xml
  usercp.php
  usercp2.php
Labels: 1.9

#3259 Working on #2972 Template Conversion to Twig Format (modcp finduser)
  inc/views/base/modcp/finduser.twig
  modcp.php
Labels: 1.9

#3258 Working on #2972 Template Conversion to Twig Format (xmlhttp)
  inc/views/base/xmlhttp/buddyselect.twig
  xmlhttp.php
Labels: 1.9

#3250 Working on #2972 Template Conversion to Twig Format (forumjump)
  inc/functions.php
  inc/views/base/misc/forumjump.twig
  inc/views/base/misc/forumjump_bit.twig
Labels: 1.9

#3252 Working on #2972 Template Conversion to Twig Format (smilieinsert)
  inc/functions.php
  inc/views/base/smilieinsert/main.twig
Labels: 1.9

#3253 Working on #2972 Template Conversion to Twig Format (footer)
  global.php
  inc/functions.php
  inc/views/base/partials/footer.twig
Labels: 1.9

#3242 Working on #2972 Template Conversion to Twig Format (usercp_avatar)
  inc/views/base/usercp/avatar.twig
  usercp.php
Labels: 1.9

#3249 Working on #2972 Template Conversion to Twig Format (mycodes)
  inc/class_parser.php
  inc/views/base/parser/mycodes/code.twig
  inc/views/base/parser/mycodes/email.twig
  inc/views/base/parser/mycodes/img.twig
  inc/views/base/parser/mycodes/php.twig
  inc/views/base/parser/mycodes/quote.twig
  inc/views/base/parser/mycodes/size.twig
  inc/views/base/parser/mycodes/smilie.twig
  inc/views/base/parser/mycodes/url.twig
  inc/views/base/parser/mycodes/video.twig
Labels: 1.9

#3243 Working on #2972 Template Conversion to Twig Format (usercp_options)
  inc/functions.php
  inc/views/base/misc/themeselect.twig
  inc/views/base/usercp/options.twig
  usercp.php
Labels: 1.9

#3264 Fixes #3263 – Missing array casting produces warning when posticons cache is empty
  inc/functions.php
Labels: 1.8

#3223 Working on #2972 Template Conversion to Twig Format (modcp_reports)
  inc/views/base/modcp/allreports.twig
  inc/views/base/modcp/allreports/item.twig
  inc/views/base/modcp/reports.twig
  inc/views/base/modcp/reports/item.twig
  modcp.php
Labels: 1.9

#3222 Working on #2972 Template Conversion to Twig Format (modcp_banning)
  inc/views/base/modcp/banning.twig
  inc/views/base/modcp/banuser.twig
  modcp.php
Labels: 1.9

#3163 For #2976 — $lang->parse()
  inc/src/Twig/Extensions/LangExtension.php
Labels: 1.9

#3225 Working on #2972 Template Conversion to Twig Format (modcp_modqueue)
  inc/views/base/modcp/modqueue/attachment.twig
  inc/views/base/modcp/modqueue/post.twig
  inc/views/base/modcp/modqueue/thread.twig
  inc/views/base/modcp/modqueue_attachments.twig
  inc/views/base/modcp/modqueue_empty.twig
  inc/views/base/modcp/modqueue_posts.twig
  inc/views/base/modcp/modqueue_threads.twig
  modcp.php
Labels: 1.9

#3266 Fix `settinggroups` spelling mistake
  install/resources/upgrade43.php
Labels: 1.8, bug

#3251 Working on #2972 Template Conversion to Twig Format (global)
  global.php
  inc/languages/english/global.lang.php
  inc/src/Twig/Extensions/ThemeExtension.php
  inc/views/base/messages/banneduser.twig
  inc/views/base/messages/base.twig
  inc/views/base/messages/boardclosed_reason.twig
  inc/views/base/messages/dst_detection.twig
  inc/views/base/messages/pmnotice.twig
  inc/views/base/modals/base.twig
  inc/views/base/modals/boardclosed.twig
  inc/views/base/modals/no_permission.twig
  inc/views/base/partials/header.twig
Labels: 1.9

#3247 Working on #2972 Template Conversion to Twig Format (modcp editprofile)
  inc/views/base/modcp/editprofile.twig
  modcp.php
Labels: 1.9

#3229 Working on #2972 Template Conversion to Twig Format (private.php)
  inc/functions_post.php
  inc/languages/english/private.lang.php
  inc/views/base/postbit/postbit.twig
  inc/views/base/private/advanced_search.twig
  inc/views/base/private/empty.twig
  inc/views/base/private/export.twig
  inc/views/base/private/export/csv.twig
  inc/views/base/private/export/html.twig
  inc/views/base/private/export/txt.twig
  inc/views/base/private/folders.twig
  inc/views/base/private/private.twig
  inc/views/base/private/private/item.twig
  inc/views/base/private/read.twig
  inc/views/base/private/results.twig
  inc/views/base/private/results/item.twig
  inc/views/base/private/send.twig
  inc/views/base/private/tracking.twig
  private.php
Labels: 1.9

#3256 Working on #2972 Template Conversion to Twig Format (miscellaneous)
  contact.php
  editpost.php
  inc/class_captcha.php
  inc/class_error.php
  inc/functions.php
  inc/views/base/layouts/master.twig
  inc/views/base/misc/attachment_icon.twig
  inc/views/base/misc/captcha/hidden.twig
  inc/views/base/misc/captcha/post.twig
  inc/views/base/misc/captcha/register.twig
  inc/views/base/misc/changeuserbox.twig
  inc/views/base/misc/codebuttons.twig
  inc/views/base/misc/debugsummary.twig
  inc/views/base/misc/loginbox.twig
  inc/views/base/misc/php_warnings.twig
  inc/views/base/misc/redirect.twig
  member.php
  moderation.php
  newreply.php
  newthread.php
  polls.php
  sendthread.php
  showthread.php
Labels: 1.9

#3248 Working on #2972 Template Conversion to Twig Format (modcp)
  inc/views/base/modcp/home.twig
  modcp.php
Labels: 1.9

#3151 Working on #2972 Template Conversion to Twig Format (misc.php)
  inc/languages/english/misc.lang.php
  inc/views/base/misc/buddypopup.twig
  inc/views/base/misc/help.twig
  inc/views/base/misc/help_helpdoc.twig
  inc/views/base/misc/helpresults.twig
  inc/views/base/misc/rules.twig
  inc/views/base/misc/smilies.twig
  inc/views/base/misc/smilies_modal.twig
  inc/views/base/misc/syndication.twig
  inc/views/base/misc/whoposted.twig
  inc/views/base/misc/whoposted_modal.twig
  misc.php
Labels: 1.9

#3244 Working on #2972 Template Conversion to Twig Format (usercp)
  inc/views/base/usercp/home.twig
  usercp.php
Labels: 1.9

#3043 Working on #2972 Template Conversion to Twig Format (index)
  inc/views/base/index/index.twig
  inc/views/base/usercp/draft_row.twig
  inc/views/base/usercp/subscribed_forum_row.twig
  inc/views/base/usercp/subscribed_thread_row.twig
  index.php
Labels: 1.9

#3254 Working on #2972 Template Conversion to Twig Format (forumbit)
  inc/functions_forumlist.php
  inc/views/base/forumbit/depth3.twig
  inc/views/base/forumbit/depth_1/cat.twig
  inc/views/base/forumbit/depth_1/last_post.twig
  inc/views/base/forumbit/depth_2/cat.twig
  inc/views/base/forumbit/depth_2/forum.twig
  inc/views/base/forumbit/subforums.twig
Labels: 1.9

#3206 Fixes #3203 Move Contact fields to Custom Profile Fields
  admin/modules/config/profile_fields.php
  admin/modules/user/users.php
  inc/datahandlers/user.php
  inc/languages/english/admin/config_profile_fields.lang.php
  inc/languages/english/admin/user_users.lang.php
  inc/languages/english/datahandler_user.lang.php
  inc/languages/english/member.lang.php
  inc/languages/english/memberlist.lang.php
  inc/languages/english/modcp.lang.php
  inc/languages/english/usercp.lang.php
  inc/views/base/member/profile.twig
  inc/views/base/member/register.twig
  inc/views/base/member/register_profilefield.twig
  inc/views/base/modcp/editprofile.twig
  inc/views/base/usercp/profile.twig
  install/index.php
  install/resources/mybb_theme.xml
  install/resources/mysql_db_inserts.php
  install/resources/mysql_db_tables.php
  install/resources/pgsql_db_tables.php
  install/resources/settings.xml
  install/resources/sqlite_db_tables.php
  member.php
  memberlist.php
  modcp.php
  usercp.php
Labels: 1.9

#3056 Working on #2972 Template Conversion to Twig Format (forumdisplay)
  forumdisplay.php
  inc/functions.php
  inc/views/base/forumdisplay/forumdisplay.twig
  inc/views/base/forumdisplay/inlinemoderation.twig
  inc/views/base/forumdisplay/password.twig
  inc/views/base/forumdisplay/thread.twig
  inc/views/base/forumdisplay/thread_deleted.twig
  inc/views/base/forumdisplay/thread_modbit.twig
  inc/views/base/forumdisplay/thread_rating.twig
Labels: 1.9

#3275 Fix ACP link in header
  inc/views/base/header/welcomeblock_member.twig
Labels: 1.9

#3286 Fixes #3170 MySQL error with strict mode if message too long - Extended
  inc/datahandlers/post.php
  install/resources/settings.xml
Labels: 1.8
