Repository mybb/mybb, pull requests merged in 2018-11, with the labels that each got.

#3487 Improve language of bans ending soon in ModCP homepage
  inc/languages/english/modcp.lang.php
  inc/views/base/modcp/home.twig
Labels: b:1.9, t:enhancement

#3479 Fix #3476 - version check failing with blank lines in content
  admin/modules/config/plugins.php
  admin/modules/home/index.php
  inc/tasks/versioncheck.php
Labels: b:1.8

#3490 Fixes #3483 Add 'exact' option to memberlist username search
  inc/languages/english/memberlist.lang.php
  install/resources/mybb_theme.xml
  memberlist.php
Labels: b:1.8

#3488 Fixes #3486 Missing Moderation Notices
  global.php
  inc/languages/english/global.lang.php
  install/resources/mybb_theme.xml
Labels: b:1.8

#3494 Twig extension to generate URLs.
  inc/src/Twig/Extensions/CoreExtension.php
  inc/src/Twig/Extensions/UrlExtension.php
  inc/src/Twig/ServiceProvider.php
Labels: b:1.9

#3480 Last poster avatars
  composer.lock
  forumdisplay.php
  inc/functions_forumlist.php
  inc/src/Twig/Extensions/CoreExtension.php
  inc/src/Twig/ServiceProvider.php
  inc/views/base/forumbit/depth_2/last_post.twig
  inc/views/base/forumdisplay/forumdisplay.twig
  inc/views/base/forumdisplay/thread.twig
  inc/views/base/partials/avatar.twig
  inc/views/base/partials/default_avatar.twig
  inc/views/base/private/export/html.twig
  inc/views/base/private/private/item.twig
  inc/views/base/private/results/item.twig
  inc/views/base/private/tracking.twig
  inc/views/base/search/results_posts_row.twig
  inc/views/base/search/results_threads_row.twig
  inc/views/base/usercp/home.twig
  inc/views/base/usercp/subscribed_forum_row.twig
  inc/views/base/usercp/subscribed_thread_row.twig
  inc/views/base/usercp/subscribed_threads.twig
  inc/views/base/usercp/subscribed_threads/row.twig
  index.php
  private.php
  search.php
  usercp.php
Labels: b:1.9

#3503 Add avatars to forum team
  inc/views/base/showteam/showteam.twig
  showteam.php
Labels: b:1.9

#3502 Fixes #3501 - lang typos in merge users
  inc/languages/english/admin/user_users.lang.php
  inc/languages/english/moderation.lang.php
Labels: b:1.8

#3505 Fixes #3504 ModCP warninglogs pagination issue
  modcp.php
Labels: b:1.8

#3493 Fixes #3419 View Own Unapproved Threads / Posts
  editpost.php
  forumdisplay.php
  inc/functions_post.php
  inc/languages/english/global.lang.php
  install/resources/settings.xml
  newreply.php
  showthread.php
  xmlhttp.php
Labels: b:1.8

#3405 Fixes #2020 Referrals Are Lost on Account Merge
  admin/modules/user/users.php
Labels: b:1.8

#3401 Fixes #3395 - Regression - Force Custom profile fields on Admins & Mods
  inc/languages/english/admin/config_profile_fields.lang.php
  member.php
Labels: b:1.8
