Repository mybb/mybb, pull requests merged in 2018-02, with the labels that each got.

#2988 Postbit — For #2972
  inc/functions_post.php
  inc/views/base/postbit/postbit.twig
  inc/views/base/postbit/postbit_attached_image.twig
  inc/views/base/postbit/postbit_attached_thumbnail.twig
  inc/views/base/postbit/postbit_attachment.twig
  inc/views/base/postbit/postbit_attachments.twig
  inc/views/base/postbit/postbit_deleted_member.twig
Labels: 1.9, enhancement

#2996 Reports — For #2972
  inc/views/base/report/report.twig
  inc/views/base/report/report_error_nomodal.twig
  inc/views/base/report/report_reasons.twig
  inc/views/base/report/report_thanks.twig
  report.php
Labels: 1.9, enhancement

#3032 Working on #2972 Template Conversion to Twig Format (member.php)
  inc/views/base/member/activate.twig
  inc/views/base/member/coppa_form.twig
  inc/views/base/member/emailuser.twig
  inc/views/base/member/login.twig
  inc/views/base/member/lostpw.twig
  inc/views/base/member/resendactivation.twig
  inc/views/base/member/resetpassword.twig
  inc/views/base/member/viewnotes.twig
  member.php
Labels: 1.9

#3008 #2972 (online.php) online user list to twig
  inc/functions_online.php
  inc/views/base/online/online.twig
  inc/views/base/online/today.twig
  online.php
Labels: 1.9

#3042 Updates for #2972
  calendar.php
  inc/views/base/calendar/dayview.twig
  inc/views/base/contact/contact.twig
  inc/views/base/managegroup/joinrequests.twig
  inc/views/base/managegroup/managegroup.twig
  inc/views/base/moderation/viewthreadnotes.twig
  inc/views/base/polls/editpoll.twig
  inc/views/base/polls/newpoll.twig
  inc/views/base/postbit/postbit.twig
  inc/views/base/sendthread/sendthread.twig
  inc/views/base/warnings/view.twig
  inc/views/base/warnings/warn.twig
  inc/views/base/warnings/warnings.twig
  managegroup.php
  memberlist.php
  moderation.php
  warnings.php
Labels: 1.9

#3039 Working on #2972 Template Conversion to Twig Format (editpost.php)
  editpost.php
  inc/views/base/editpost/editpost.twig
Labels: 1.9

#3036 Working on #2972 Template Conversion to Twig Format (newreply.php)
  inc/views/base/newreply/newreply.twig
  newreply.php
Labels: 1.9

#3035 Working on #2972 Template Conversion to Twig Format (newthread.php)
  inc/functions.php
  inc/views/base/newthread/newthread.twig
  newthread.php
Labels: 1.9

#3033 Working on #2972 Template Conversion to Twig Format (member profile)
  inc/views/base/member/profile.twig
  member.php
Labels: 1.9

#3031 Updating user CP email, password and username pages to use Twig
  inc/views/base/usercp/changename.twig
  inc/views/base/usercp/email.twig
  inc/views/base/usercp/password.twig
  usercp.php
Labels: 1.9, s:fixed

#3030 Updating user CP signature page to use Twig
  inc/views/base/usercp/editsig.twig
  inc/views/base/usercp/editsig_suspended.twig
  usercp.php
Labels: 1.9, s:fixed

#3029 Updating user CP buddy/ignore list to use Twig
  inc/src/Twig/Extensions/LangExtension.php
  inc/views/base/usercp/drafts.twig
  inc/views/base/usercp/drafts/row.twig
  inc/views/base/usercp/editlists.twig
  inc/views/base/usercp/editlists/buddy_list.twig
  inc/views/base/usercp/editlists/ignore_list.twig
  inc/views/base/usercp/editlists/received_request_row.twig
  inc/views/base/usercp/editlists/received_requests.twig
  inc/views/base/usercp/editlists/sent_request_row.twig
  inc/views/base/usercp/editlists/sent_requests.twig
  inc/views/base/usercp/editlists/user.twig
  inc/views/base/usercp/subscribed_forums.twig
  inc/views/base/usercp/subscribed_forums/row.twig
  inc/views/base/usercp/subscribed_threads.twig
  inc/views/base/usercp/subscribed_threads/row.twig
  usercp.php
Labels: 1.9, s:fixed
