Repository mybb/mybb, pull requests merged in 2019-06, with the labels that each got.

#3655 Fixes #3540 Omit unwanted links / buttons (v.2)
  global.php
  inc/functions_post.php
  install/resources/mybb_theme.xml
  jscripts/general.js
  member.php
  usercp.php
Labels: s:in-progress, t:enhancement

#3719 Fixes #3718 Uncaught Error when changing usernames
  install/resources/mybb_theme.xml
  usercp.php
Labels: b:1.8

#3708 Fix #3707 - "&hellip;" is displayed in redirect button
  admin/inc/functions.php
  admin/modules/forum/management.php
  admin/modules/tools/recount_rebuild.php
Labels: b:1.8

#3728 Add the new `funding.yml` file to show a sponsor button on GitHub
  .github/FUNDING.yml
Labels: s:feedback
